baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "xmin"

[menu]

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = -110